### ISSUE TITLE
Please close, I messed it up

### ISSUE THREAD

**Issue by bloodbank** [duzun/hQuery.php#11]
Please close, I messed up.

**Comment by duzun** [comment]
$doc = hQuery::fromUrl(
                $url
              , array(
                    'Accept'     => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
                    'User-Agent' => 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36',
                )
            );
