### ISSUE TITLE
How do you find Element by attribute

### ISSUE THREAD

**Issue by dragonattack** [duzun/hQuery.php#12]
`input[name=title]` doesn't seem to work.

How you get that?

**Comment by duzun** [comment]
On my ToDo list there is 
> - Improve selectors to be able to select by attributes


Meanwhile you can use:

```php
$title_input = $doc->find('input', 'name=title');
```

**Comment by phpclub** [comment]
Not fork, need array
$title_input = $doc->find('input', array('name'=>'title'));

**Comment by duzun** [comment]
With v3.0.0 (in 718e4ad7a4b088ce0b0de383b7d3d18546f7d9cf), you can use attribute selector.
