### ISSUE TITLE
Redirection Follow: problem

### ISSUE THREAD

**Issue by cure85** [duzun/hQuery.php#13]
Hello,

I have noticed some problems with redirection. The library fails on me and also on the demo: [https://duzun.me/playground/hquery](https://duzun.me/playground/hquery)

Example URLs to check:
http://sorellhotels.com
http://bücher.ch
http://ipet.ch

As example to explain the problem and my debuging I will use http://sorellhotels.com

This url has 3 redirections as follows:
- 301: http://sorellhotels.com
- 301: https://sorellhotels.com
- 200: https://sorellhotels.com/de

hQuery does this:
- 301: http://sorellhotels.com
- 301: https://sorellhotels.com/
FAIL: https://tls/de

He changes the host wrong ... Instead of "sorellhotels.com" he uses "tls"

Can you please check this? Thx

Best regards

**Comment by duzun** [comment]
Hi @cure85 !

Thanks for reporting this issue.

This is happening because of relative URL used for redirect: `location: /en`

I'm going to fix it...
