### ISSUE TITLE
There's an error on test

### ISSUE THREAD

**Issue by bildgee** [duzun/hQuery.php#17]
Fatal error: Using $this when not in object context in C:\xampp\htdocs\scraper\duzun.me_playground_hquery.php on line 13

**Comment by duzun** [comment]
Thank @bildgee for reporting, my bad, should have noted that this is not intended to be run as is, but is merely source code of my [playground](https://duzun.me/playground/hquery), as requested by many people.

I should create more examples so that anyone can run and test how it works.
