### ISSUE TITLE
how i get a value from a span?

### ISSUE THREAD

**Issue by Haizone** [duzun/hQuery.php#19]
hi great stuff and very fast!!

but how i can get a value from a sapn:
i have that line in the html page:
 `<span class="price_value" itemprop="price">3,850 ₪</span>`

ho wi get the value ? (that:3,850 ₪)
i need the faster way to get the value.

i try that:
`$doc->find('span .price_value')->text()`

and its work
but maybe have a better way to get the info or faster

and if i do a 3-5 times reffresh i get that error:
Fatal error: Call to a member function text() on null in

how i can fix that?

thanks :)

**Comment by duzun** [comment]
If there is no HTML to strip from `span`, use `->html()` method instead.

Also, if you need to get values from multiple spans, you can use `foreach` like this:

```php
$res = [];
foreach($doc->find('span .price_value') as $span) {
     $res[] = $span->html()
}
```

Here is the `text()` method:

```php
   /**
    * @return string .innerText
    */
    public function text($id=NULL) {
        return html_entity_decode(strip_tags($this->html($id)), ENT_QUOTES);/* ??? */
    }
```

Maybe someone could suggest a better way of doing this?

**Comment by duzun** [comment]
> and if i do a 3-5 times reffresh i get that error:
Fatal error: Call to a member function text() on null in

I ques this is due to reasons outside hQuery.
It is most likely that `$doc` holds an empty HTML document.
You should check for `NULL` the return value of `$doc->find()` before using it.

```php
$price = $doc->find('span .price_value');
if ( empty($price) ) {
     echo "Couldn't find any .price_value";
}
else {
     echo "Price is " . $price->html();
}
```
