### ISSUE TITLE
how hasClass is implemented?

### ISSUE THREAD

**Issue by dragonattack** [duzun/hQuery.php#21]
I see mentions in the code, could you please give an example of how should I use it.
Thanks! Great lib and I still use it :)

**Comment by duzun** [comment]
Hhm. Good point!
It has been a `protected` method on document class, never exposed on element class.
I've added the `hQuery_Element::hasClass($className)` method and updated [README.md](https://github.com/duzun/hQuery.php#processing-the-results).

**Comment by dragonattack** [comment]
I've added new independent method hasClass to _Element as temporary workaround, but your changes are more solid and ... those good rewrites) Thanks for your time, Dumitru!)
