### ISSUE TITLE
Error on similar attributes

### ISSUE THREAD

**Issue by mrgingles** [duzun/hQuery.php#22]
Hi! 
I found an error when there are similar attributes on the same tag.

If you have `src` and `src2` attribute on an `img` tag and try to use `->attr('src')`, it founds nothing. If you use `->attr('src2')` it found the attr text as expected.

**Comment by duzun** [comment]
I've added some unit-tests to prove `->attr('src2')` works exactly the same as `->attr('src')` or any other attribute.

Please, check you code around `hQuery` and the HTML sources you are parsing to find the issue!

Regards

**Comment by mrgingles** [comment]
Hi @duzun 
I can confirm that the problem is not on `src2` as attribute, but the problem is that if you have SIMILAR attributes on the same tags (eg. `src` and `src2` - `<img src='xxx' src2='yyy'>`), hQuery can't get the `src` value (but it works on `src2`)

**Comment by duzun** [comment]
My last commit pruves just the opposite!

Can you provide some code example?
