### ISSUE TITLE
Cache needed?

### ISSUE THREAD

**Issue by xmadscientist** [duzun/hQuery.php#27]
When using this library, is setting the cache folder absolutely necessary? What would happen if we didn't put it?

**Comment by duzun** [comment]
No, it is not mandatory to use cache.

Actually, cache only affects `hQuery::fromURL()`, and if you don't use it, every call to this method would result in a new request, but with cache this method would try to use the data from cache when present.

In general, you can use any other method to make requests outside of `hQuery` and then just feed the resulting HTML to `hQuery::fromHTML($html, $url=NULL)`.
