### ISSUE TITLE
Exception Error warning

### ISSUE THREAD

**Issue by designbyjr** [duzun/hQuery.php#28]
I use symfony 3.2 and got this warning.

> php.DEBUG: Notice: Undefined index: CONTENT_ENCODING {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":8,\"file\":\"/../USER/MYPROJECT/vendor/duzun/hquery/hquery.php\",\"line\":2967})"} 

> Notice: Undefined index: method also appears in line 2751.
Can you please check this?

**Comment by duzun** [comment]
These are just Notices that I intentionally hide with `@`.

I've updated the code to not have these notices in [#fff3610](https://github.com/duzun/hQuery.php/commit/fff3610d5ca8f1c6761add6b67d780d0cb702b1f).

**Comment by designbyjr** [comment]
Thank you
