### ISSUE TITLE
Does it work? multiple class

### ISSUE THREAD

**Issue by gibex** [duzun/hQuery.php#3]
I'm trying to get information from .typeHighlight class from link below:
 trulia.com/property/1061429905-West-End-Heights-273-Barfield-Ave-SW-Atlanta-GA-30310

Instead of 11 nodes, I get 5. It's odd because if I use a simple html, I get the right results.

**Comment by duzun** [comment]
There is a bug. I'll look into it.
I started writeing [unit tests](./1) for this lib to find as many bugs as possible.

Thanks @gibex for pointing it out.

**Comment by gibex** [comment]
Found out that class_index has less elements for that tag. ‎I guess it's a problem in indexing classes.                                                                                                                                                                                                                                                                                                                                         Sent from Zmeura 10                                                                                                                                                                                                                From: Dumitru UzunSent: Thursday, March 5, 2015 16:06To: duzun/hQuery.phpReply To: duzun/hQuery.phpCc: Gabriel DorofteiSubject: Re: [hQuery.php] Does it work? multiple class (#3)There is a bug. I'll look into it.
I started writeing unit tests for this lib to find as many bugs as possible.

Thanks @gibex for pointing it out.

—Reply to this email directly or view it on GitHub.

**Comment by duzun** [comment]
I found the reason. It is due to malformeed HTML:
```html
<img class="mapImg" src="http://static.trulia-cdn.com/images/icons/map_icon_70x70.png"">
```
Notice oppening quote before closing > ?

What do you think would be the best workaround ?

**Comment by duzun** [comment]
I improved the `::html_findTagClose()` method, so that it behaves closer to a normal broser.
Now it finds 9 nodes. If you search on client side using `jQuery('.typeHighlight')`, you also get 9 nodes, even though there are 11 nodes with this class in HTML.

Here is the commit [4db7e4d](https://github.com/duzun/hQuery.php/commit/4db7e4d8f6476364c6ce18646070ebd51306d4af).

**Comment by duzun** [comment]
Actualy two nodes with `.typeHighlight` are inside `<script>` tags, they are not supposed to be fetched by `.find()`.

**Comment by gibex** [comment]
Thank you
