### ISSUE TITLE
Is there a way to get the image full path?

### ISSUE THREAD

**Issue by mirr** [duzun/hQuery.php#35]
How to get the full path of image from this?

`<meta content="/logo-og.png" data-react-helmet="true" property="og:image" />`

**Comment by duzun** [comment]
Given the document `$doc` and the node `$m`:

```php
$doc->url2abs($m->attr('content'));
```

By default `href` and `src` attributes are converted to full path urls.

**Comment by duzun** [comment]
Here is an example in [hQuery.Test.php](https://github.com/duzun/hQuery.php/blob/master/tests/hQuery.Test.php#L230..L237).
