### ISSUE TITLE
ErrorException: reset() expects parameter 1 to be array

### ISSUE THREAD

**Issue by mislam** [duzun/hQuery.php#40]
https://github.com/duzun/hQuery.php/blob/cbe7a6d4d8686fed31e2c489afa79ab6d514df11/src/hQuery/Element.php#L161-L166

I get the following error:

> **ErrorException: reset() expects parameter 1 to be array, boolean given in /home/vagrant/sellercrew/vendor/duzun/hquery/src/hQuery/Element.php:163**

My best guess here is that this assumes the class to be present in at least one place in the whole DOM. If not present, the $ret becomes false.

**Comment by duzun** [comment]
Thanks for catching this bug!

Fixed in [1ee94592](https://github.com/duzun/hQuery.php/commit/1ee945922487e4d9f791f6c9f792407665530b21).

It was an interesting edge case:

```php
$elementWithAnyClass->hasClass(['existing-in-doc', 'non-existing-in-doc']);
```
