### ISSUE TITLE
Get Attribute value

### ISSUE THREAD

**Issue by fotovat** [duzun/hQuery.php#45]
How we can get attribute value from this string ?

` <div id="cerberus-data-metrics" style="display: none;" data-asin="B00EAHSBV4" data-asin-price="24.55" data-asin-shipping="0" data-asin-currency-code="USD" data-substitute-count="-1" data-device-type="WEB" data-display-code="Asin is not eligible because it has a retail offer" ></div>`

following does not work:
`            $p = $doc->find_text('#cerberus-data-metrics','data-asin-price');
`

**Comment by duzun** [comment]
Did you check the [Processing the results](https://github.com/duzun/hQuery.php#processing-the-results) from README or [examples/](https://github.com/duzun/hQuery.php/tree/master/examples) folder?

`find_text()` method doesn't exist.

Here is what you need:

```php
$div = $doc->find('#cerberus-data-metrics');
return $div->attr('data-asin-price');

// or get all the attributes of <div /> as an array
return $div->attr();
```

**Comment by fotovat** [comment]
Appreciated. Great library.

**Comment by duzun** [comment]
With the latest update, you could find elements by attributes:

```php
return $doc->find('[data-asin-price]')->attr('data-asin-price');
```
