### ISSUE TITLE
:nth-child support

### ISSUE THREAD

**Issue by dbeja** [duzun/hQuery.php#51]
Hi,

I tried to use :nth-child but it seems to not be working.

The rule I'm using is this one:
`.product > .row > .col-12 > .row:nth-child(2)`

Thanks

**Comment by duzun** [comment]
The `:nth-child` is in my ToDo list.
At the moment you can use `:eq(2)` for your use-case:

`.product > .row > .col-12 > .row:nth-child(2)`

**Comment by dbeja** [comment]
Perfect, thanks, :eq works fine for what I need.
