### ISSUE TITLE
fromHTML is returning {"headers":null,"tag_map":null}

### ISSUE THREAD

**Issue by Bholtland** [duzun/hQuery.php#54]
I'm using CURL to fetch a HTML doc. Then, I use hQuery::fromHTML to parse the document. When I display the value I get the following JSON data: {"headers":null,"tag_map":null}.

I figured something must be going wrong in hQuery::fromHTML, since the html document displays fine after fetching it with CURL.

When I use hQuery::fromUrl(), I receive the same object.

**Comment by duzun** [comment]
`hQuery::fromHTML()` is only returning an instance of `hQuery`, nothing else.
You can see that for yourself from the [source code](https://github.com/duzun/hQuery.php/blob/master/src/hQuery.php#L69..L101).

How did you get that output? Did you use something like `json_encode($doc)`?
Looks like `tag_map` and `headers` are the only public properties of the `hQuery` instance.

**Comment by Bholtland** [comment]
Indeed, i was using json_encode($doc) to print the value. Sorry, i should've mentioned that.  I tested this with another web page and that worked fine. 

Could it have something to do with the web page itself? The weird thing is that the HTML that i feed it, is perfectly valid HTML before i use hQuery::fromHTML(). I wish i could send you the source, but i'm afraid i'm not allowed to do that.

Thanks for the quick reply by the way.

**Comment by duzun** [comment]
You are not supposed to print the `$doc` instance directly, but rather use it to extract the data you need from the document.

If you want to get a quick view of what is inside the `$doc` instance, you can use `echo json_encode($doc->_info())`.

See the [README -> Processing the results](https://github.com/duzun/hQuery.php#processing-the-results) or [examples/playground.php](https://github.com/duzun/hQuery.php/blob/master/examples/playground.php) to get an idea what else you can do with a `$doc` instance. 
Also, the [unit-tests](https://github.com/duzun/hQuery.php/blob/master/tests/hQuery.Test.php) are a good source of documentation.

I know, this library is poorly documented. 
I would make proper documentation should I have more free time :)

**Comment by Bholtland** [comment]
Okay thanks for your clear explanation :) I will see if I can fix it, and will post here, should I have useful information.

**Comment by duzun** [comment]
Thanks and Good luck!
