### ISSUE TITLE
How to parse this?

### ISSUE THREAD

**Issue by katesaikishore** [duzun/hQuery.php#66]
`<div class=" "> `
**This line does not have class how to access this?** div. ?

**Comment by duzun** [comment]
Technically speaking, you are right, this `div` does not have a class.

Did you try `div[class=" "]` selector?

**Comment by duzun** [comment]
See [#8b8fd](https://github.com/duzun/hQuery.php/commit/8b8fd36ed52dd0a46a813674abef82ee1b78cd3c)
