### ISSUE TITLE
Fixing types

### ISSUE THREAD

**Issue by FluffyDiscord** [duzun/hQuery.php#67]
Hello, could you please remove the PSR-0 aliases and fix return types for quite a few functions ? It's rather annoying to work with php 8.1 with this as functions tend to return different data types that do not correspond to the comments.

Libraries like `rector/rector` fail to analyze classes using your library because of the PSR-0 and IDEs like PhpStorm incorrectly hint return types, because they are wrong in the annotations/comments.

**Comment by duzun** [comment]
Hi,
Thanks for the comments.
I'd appreciate if you could test the latest version and show some examples of wrong types.

**Comment by duzun** [comment]
Fixed in [PSR-0 class names cleanup](https://github.com/duzun/hQuery.php/commit/dbd05025322f74a5d7ea6d32287f57813d295a10).
