### ISSUE TITLE
Parsing error when meta Content-Type has incorrect charset name

### ISSUE THREAD

**Issue by PavelFil** [duzun/hQuery.php#93]
Hello. This code breaks the parsing:
```php
hQuery::fromHTML('<html><head><meta http-equiv="Content-Type" content="text/html; charset=uft-8" /></head></html>');
```
Output:
```
PHP Fatal error:  Uncaught Exception: E_WARNING iconv(): Wrong encoding, conversion from "UFT-8" to "UTF-8" is not allowed
 IN /vendor/duzun/hquery/src/hQuery/Node.php ON 1435

 in /init.php:32
Stack trace:
#0 [internal function]: myErrorHandler()
#1 /vendor/duzun/hquery/src/hQuery/Node.php(1435): iconv()
#2 /vendor/duzun/hquery/src/hQuery/HTML_Index.php(234): duzun\hQuery\Node::convert_encoding()
#3 /vendor/duzun/hquery/src/hQuery.php(86): duzun\hQuery\HTML_Index->__construct()
#4 /test.php(4): duzun\hQuery::fromHTML()
```
Maybe we can write parsing errors like this in static variable `hQuery::last_errors`.

**Comment by duzun** [comment]
WDYT of https://github.com/duzun/hQuery.php/commit/80fb213d6774607cddefa7f9e2519a8473101f90?

**Comment by duzun** [comment]
Not directly related, but for the case when the charset is not present in the HTML, it could be read from HTTP headers: https://github.com/duzun/hQuery.php/commit/e18b65e19eb4802b7ac3a4746fd1ea5ba294304d

**Comment by PavelFil** [comment]
Thank you. Now it doesn't catch fatal error. Also, using HTTP headers is very helpful.
