### ISSUE TITLE
Non-obvious behavior for  ->attr('href') method, if tag <base> are present

### ISSUE THREAD

**Issue by PavelFil** [duzun/hQuery.php#95]
This code:
```php
use duzun\hQuery;
$html = '<html>
    <head>
        <base href="https://example.com/" />
    <head>
    <body>
        <a href="#hash">link</a>
    </body>
</html>';
$hQuery = hQuery::fromHTML($html);
$links = $hQuery->find('a');
foreach($links as $link) {
    var_dump($link->attr('href'));
    var_dump($link->href);
}
```
returns:
```
string(25) "https://example.com/#hash"
string(25) "https://example.com/#hash"
```
So there is no way to receive raw `href` attribute.
We must add `$hQuery->baseURI(null);` after `$hQuery = hQuery::fromHTML($html);` to prevent links modifying.

I suspect, this is some old functional that can be removed.

**Comment by duzun** [comment]
Hmmm, this is a very good catch!

I've tried to align hQuery to the browser and jQuery behavior in [#48ad78](https://github.com/duzun/hQuery.php/commit/48ad7846838093839f03dc5f60562c1b4a9dc80c):

- `$node->attr('href')` - always the raw value.
- `$node->href` - always the evaluated/resolved value.

This is a potentially breaking change for some code out there.

I've incremented the minor version, though strictly speaking should increase the major version. On the other hand it is no a big change, thus I'm hesitant to increase the major version.
